-- MySQL Script generated by MySQL Workbench
-- Sun Oct 22 00:52:16 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema accWe_hospital_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `accWe_hospital_db` ;

-- -----------------------------------------------------
-- Schema accWe_hospital_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `accWe_hospital_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_czech_ci ;
USE `accWe_hospital_db` ;

-- -----------------------------------------------------
-- Table `accWe_hospital_db`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accWe_hospital_db`.`room` (
  `room_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`room_name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accWe_hospital_db`.`doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accWe_hospital_db`.`doctor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `age` INT NOT NULL,
  `email` VARCHAR(255) NULL,
  `room_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_doctor_room1_idx` (`room_name` ASC) VISIBLE,
  CONSTRAINT `fk_doctor_room1`
    FOREIGN KEY (`room_name`)
    REFERENCES `accWe_hospital_db`.`room` (`room_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accWe_hospital_db`.`patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accWe_hospital_db`.`patient` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `age` INT NOT NULL,
  `email` VARCHAR(255) NULL,
  `doctor_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_patient_doctor_idx` (`doctor_id` ASC) VISIBLE,
  CONSTRAINT `fk_patient_doctor`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `accWe_hospital_db`.`doctor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accWe_hospital_db`.`appointment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accWe_hospital_db`.`appointment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `starts_at` DATETIME NOT NULL,
  `finishes_at` DATETIME NOT NULL,
  `patient_id` INT NOT NULL,
  `doctor_id` INT NOT NULL,
  `room_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_appointment_patient1_idx` (`patient_id` ASC) VISIBLE,
  INDEX `fk_appointment_doctor1_idx` (`doctor_id` ASC) VISIBLE,
  INDEX `fk_appointment_room1_idx` (`room_name` ASC) VISIBLE,
  CONSTRAINT `fk_appointment_patient1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `accWe_hospital_db`.`patient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_appointment_doctor1`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `accWe_hospital_db`.`doctor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_appointment_room1`
    FOREIGN KEY (`room_name`)
    REFERENCES `accWe_hospital_db`.`room` (`room_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `accWe_hospital_db` ;

-- -----------------------------------------------------
-- Placeholder table for view `accWe_hospital_db`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accWe_hospital_db`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `accWe_hospital_db`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `accWe_hospital_db`.`view1`;
USE `accWe_hospital_db`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
